name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get_version
        name: Get Version
        uses: battila7/get-version-action@v2
      - name: Release
        uses: eskatos/gradle-command-action@v1
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        with: 
          arguments: publishToSonatype closeSonatypeStagingRepository
          # when release build is settled, switch to: arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
          dependencies-cache-enabled: true
